<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { NAlert, NButton, NCard, NConfigProvider, NEmpty, NForm, NFormItem, NInput, NLayout, NLayoutContent, NLayoutHeader, NProgress, NSpin, NTag, darkTheme } from 'naive-ui'
type Entry = { name: string; directory: boolean; size: number; modified: string }
const user = ref<any>(null), setupRequired = ref(false), insecure = ref(false), loading = ref(true), error = ref(''), username = ref(''), password = ref(''), path = ref(''), entries = ref<Entry[]>([]), showHidden = ref(localStorage.getItem('ew-hidden') === 'true'), dark = ref(localStorage.getItem('ew-theme') === 'dark' || (!localStorage.getItem('ew-theme') && matchMedia('(prefers-color-scheme: dark)').matches))
const { locale } = useI18n()
async function api(url: string, init?: RequestInit) { const response = await fetch(url, { credentials: 'include', ...init }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Request failed'); return data }
async function refresh() { loading.value=true; error.value=''; try { const me=await api('/api/v1/auth/me'); user.value=me.user; insecure.value=me.insecure; await browse() } catch { const status=await api('/api/v1/setup/status'); setupRequired.value=status.required; insecure.value=status.insecure } finally { loading.value=false } }
async function submitSetup() { try { await api('/api/v1/setup',{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'fetch'},body:JSON.stringify({username:username.value,password:password.value})}); await refresh() } catch(e:any){error.value=e.message} }
async function login() { try { await api('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'fetch'},body:JSON.stringify({username:username.value,password:password.value})}); await refresh() } catch(e:any){error.value=e.message} }
async function browse() { const data=await api('/api/v1/files?path='+encodeURIComponent(path.value)); entries.value=data.entries.filter((entry:Entry)=>showHidden.value||!entry.name.startsWith('.')).sort((a:Entry,b:Entry)=>a.name.localeCompare(b.name)) }
function open(entry:Entry){if(entry.directory){path.value=path.value?`${path.value}/${entry.name}`:entry.name; browse()}}
function formatSize(size:number){if(size<1024)return `${size} B`;if(size<1024*1024)return `${(size/1024).toFixed(1)} KB`;return `${(size/1024/1024).toFixed(1)} MB`}
function toggleTheme(){dark.value=!dark.value;localStorage.setItem('ew-theme',dark.value?'dark':'light')}
function toggleHidden(){showHidden.value=!showHidden.value;localStorage.setItem('ew-hidden',String(showHidden.value));browse()}
function toggleLocale(){locale.value=locale.value==='en'?'zh-CN':'en';localStorage.setItem('ew-locale',locale.value)}
const title=computed(()=>path.value||'My files'); onMounted(refresh)
</script>
<template>
  <n-config-provider :theme="dark ? darkTheme : null"><n-layout class="app-shell"><n-layout-header bordered class="topbar"><div class="brand"><span class="brand-mark">EW</span><span>easy-webdav</span></div><div class="top-actions"><n-button quaternary @click="toggleLocale">{{ locale === 'en' ? '中文' : 'EN' }}</n-button><n-button v-if="user" quaternary @click="toggleTheme">{{ dark ? 'Light' : 'Dark' }}</n-button><n-button v-if="user" quaternary @click="toggleHidden">{{ showHidden ? 'Hide dotfiles' : 'Show dotfiles' }}</n-button><n-button v-if="user" quaternary @click="api('/api/v1/auth/logout',{method:'POST',headers:{'X-Requested-With':'fetch'}}).then(()=>refresh())">Sign out</n-button></div></n-layout-header><n-layout-content class="content"><n-spin :show="loading"><n-alert v-if="insecure" type="warning" class="alert">This connection is not encrypted.</n-alert><section v-if="!user" class="auth-wrap"><n-card class="auth-card"><div class="eyebrow">PRIVATE FILE WORKSPACE</div><h1>{{ setupRequired ? 'Create your administrator' : 'Welcome back' }}</h1><p class="muted">{{ setupRequired ? 'Set up the first account to secure this server.' : 'Sign in to browse and manage your files.' }}</p><n-alert v-if="error" type="error" class="alert">{{ error }}</n-alert><n-form @submit.prevent="setupRequired ? submitSetup() : login()"><n-form-item label="Username"><n-input v-model:value="username" autocomplete="username" /></n-form-item><n-form-item label="Password"><n-input v-model:value="password" type="password" show-password-on="click" autocomplete="current-password" /></n-form-item><n-button type="primary" attr-type="submit" block>{{ setupRequired ? 'Create administrator' : 'Sign in' }}</n-button></n-form></n-card></section><section v-else class="workspace"><div class="workspace-head"><div><div class="eyebrow">FILE BROWSER</div><h1>{{ title }}</h1><div class="crumb">/ {{ path }}</div></div><div class="usage"><span>Storage</span><n-progress type="line" :percentage="0" :show-indicator="false" /></div></div><div class="toolbar"><n-button @click="path='';browse()">Root</n-button><n-button @click="browse">Refresh</n-button><n-tag round>{{ entries.length }} items</n-tag></div><n-empty v-if="!entries.length" description="This folder is empty"/><div v-else class="file-list"><button v-for="entry in entries" :key="entry.name" class="file-row" @dblclick="open(entry)"><span class="file-icon">{{ entry.directory ? 'DIR' : 'FILE' }}</span><span class="file-name">{{ entry.name }}</span><span class="file-size">{{ entry.directory ? 'Folder' : formatSize(entry.size) }}</span><span class="file-date">{{ new Date(entry.modified).toLocaleDateString() }}</span></button></div></section></n-spin></n-layout-content></n-layout></n-config-provider>
</template>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#16302e;background:#f4faf8}*{box-sizing:border-box}body{margin:0;min-width:320px}button{cursor:pointer}.app-shell{min-height:100vh;background:#f4faf8}.topbar{height:68px;padding:0 5vw;display:flex;align-items:center;justify-content:space-between;background:#fff}.brand,.top-actions,.toolbar{display:flex;align-items:center;gap:12px}.brand{font-weight:700}.brand-mark{display:grid;place-items:center;width:30px;height:30px;background:#0d9488;color:#fff;font-size:11px;letter-spacing:.08em}.content{max-width:1180px;width:90%;margin:0 auto;padding:56px 0}.auth-wrap{min-height:68vh;display:grid;place-items:center}.auth-card{width:min(440px,100%);padding:12px}.auth-card h1,.workspace h1{margin:8px 0;font-size:clamp(28px,4vw,44px);letter-spacing:0}.muted,.crumb{color:#5d7471}.eyebrow{color:#0d9488;font-size:12px;font-weight:750;letter-spacing:.14em}.alert{margin:18px 0}.workspace-head{display:flex;justify-content:space-between;gap:24px;align-items:flex-end;border-bottom:1px solid #cce3df;padding-bottom:26px}.usage{width:180px;color:#5d7471;font-size:12px}.toolbar{padding:18px 0}.file-list{border-top:1px solid #cce3df}.file-row{width:100%;min-height:58px;display:grid;grid-template-columns:58px 1fr 100px 120px;gap:12px;align-items:center;text-align:left;border:0;border-bottom:1px solid #dbece9;background:transparent;color:inherit;padding:0 12px;transition:background .18s ease}.file-row:hover,.file-row:focus-visible{background:#e5f5f1;outline:none}.file-icon{font-size:10px;color:#0d9488;font-weight:800;letter-spacing:.08em}.file-size,.file-date{color:#66807c;font-size:13px}@media(max-width:600px){.content{padding:32px 0}.workspace-head{align-items:flex-start;flex-direction:column}.usage{width:100%}.file-row{grid-template-columns:44px 1fr 70px}.file-date{display:none}.topbar{padding:0 20px}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style>
